services:
  - type: web
    name: monitoramento-simcosta
    env: r
    plan: free
    runtime: r
    buildCommand: Rscript requirements.R
    startCommand: R -e 'shiny::runApp(appDir = ".", host = "0.0.0.0", port = 8080)'
    envVars:
      - key: RENV_CONFIG_REPOS_OVERRIDE
        value: https://cran.rstudio.com/
